-- Run in the dedicated SQL pool created by Terraform
CREATE SCHEMA dbo;
GO

CREATE TABLE dbo.DimStore (
    StoreKey INT IDENTITY(1,1) PRIMARY KEY,
    StoreId NVARCHAR(10) NOT NULL,
    StoreName NVARCHAR(100) NULL
)
WITH (DISTRIBUTION = REPLICATE, CLUSTERED COLUMNSTORE INDEX);
GO

CREATE TABLE dbo.DimProduct (
    ProductKey INT IDENTITY(1,1) PRIMARY KEY,
    ProductId NVARCHAR(20) NOT NULL,
    Category NVARCHAR(50) NULL,
    SubCategory NVARCHAR(50) NULL
)
WITH (DISTRIBUTION = HASH(ProductId), CLUSTERED COLUMNSTORE INDEX);
GO

CREATE TABLE dbo.FactSales (
    TransactionId NVARCHAR(50) NOT NULL,
    TransactionDT DATETIME2 NOT NULL,
    StoreId NVARCHAR(10) NOT NULL,
    ProductId NVARCHAR(20) NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(10,2) NOT NULL,
    PaymentType NVARCHAR(20) NOT NULL
)
WITH (DISTRIBUTION = HASH(ProductId), CLUSTERED COLUMNSTORE INDEX);
GO