name: "Terraform Apply"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_VAR_sql_admin_password: ${{ secrets.SYNAPSE_SQL_ADMIN_PASSWORD }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment:
      name: production  # Create this environment in repo settings
      # Add manual reviewers/approvers to enforce approval

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        run: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init -backend-config=backend.yaml

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infra/terraform

      - name: Terraform Apply
        working-directory: infra/terraform
        run: terraform apply tfplan
